export const REGISTRATION_ROUTE = '/registration'
export const LOGIN_ROUTE = '/login'
export const MAIN_ROUTE = '*'
export const GAME_ROUTE = '/game/:gameId'
export const GAMEINFO_ROUTE = '/gameInfo/:gameId'